import moment from "moment";

export const theme = {
  colors:{
    dark: '#011627',
    light: '#fdfffc',
    main: '#1890ff',
    mainLight: '#A8DADC',
    mainMuted: '#457B9D',
    accent: '#ff9f1c',
    grey: '#d3d3d3'
  }
};
export const headers = {
  ricoverati_con_sintomi: 'Ricoverati con Sintomi',
  terapia_intensiva: 'Terapia Intensiva',
  totale_ospedalizzati: 'totale Ospedalizzati',
  isolamento_domiciliare: 'Isolamento Domiciliare',
  totale_positivi: 'Totale Positivi',
  variazione_totale_positivi: 'Variazione Totale Positiivi',
  nuovi_positivi: 'Nuovi Positivi',
  dimessi_guariti: 'Dimessi Guariti',
  deceduti: 'Deceduti',
  totale_casi: 'Totale Casi',
  tamponi: 'Tamponi',
};

export const regionHeaders = {
  1: 'Piemonte',
  2: "Valle d'Aosta",
  3: 'Lombardia',
  4: 'P. A. Trento e Bolzano',
  5: 'Veneto',
  6: 'Friuli Venezia Giulia',
  7: 'Liguria',
  8: 'Emilia Romagna',
  9: 'Toscana',
  10: 'Umbria',
  11: 'Marche',
  12: 'Lazio',
  13: 'Abruzzo',
  14: 'Molise',
  15: 'Campania',
  16: 'Puglia',
  17: 'Basilicata',
  18: 'Calabria',
  19: 'Sicilia',
  20: 'Sardegna',
};

export const districtsHeaders = {
  1: "Torino",
  2: "Vercelli",
  3: "Novara",
  4: "Cuneo",
  5: "Asti",
  6: "Alessandria",
  7: "Aosta",
  8: "Imperia",
  9: "Savona",
  10: "Genova",
  11: "La Spezia",
  12: "Varese",
  13: "Como",
  14: "Sondrio",
  15: "Milano",
  16: "Bergamo",
  17: "Brescia",
  18: "Pavia",
  19: "Cremona",
  20: "Mantova",
  21: "Bolzano",
  22: "Trento",
  23: "Verona",
  24: "Vicenza",
  25: "Belluno",
  26: "Treviso",
  27: "Venezia",
  28: "Padova",
  29: "Rovigo",
  30: "Udine",
  31: "Gorizia",
  32: "Trieste",
  33: "Piacenza",
  34: "Parma",
  35: "Reggio nell'Emilia",
  36: "Modena",
  37: "Bologna",
  38: "Ferrara",
  39: "Ravenna",
  40: "ForlÃ¬-Cesena",
  41: "Pesaro e Urbino",
  42: "Ancona",
  43: "Macerata",
  44: "Ascoli Piceno",
  45: "Massa Carrara",
  46: "Lucca",
  47: "Pistoia",
  48: "Firenze",
  49: "Livorno",
  50: "Pisa",
  51: "Arezzo",
  52: "Siena",
  53: "Grosseto",
  54: "Perugia",
  55: "Terni",
  56: "Viterbo",
  57: "Rieti",
  58: "Roma",
  59: "Latina",
  60: "Frosinone",
  61: "Caserta",
  62: "Benevento",
  63: "Napoli",
  64: "Avellino",
  65: "Salerno",
  66: "L'Aquila",
  67: "Teramo",
  68: "Pescara",
  69: "Chieti",
  70: "Campobasso",
  71: "Foggia",
  72: "Bari",
  73: "Taranto",
  74: "Brindisi",
  75: "Lecce",
  76: "Potenza",
  77: "Matera",
  78: "Cosenza",
  79: "Catanzaro",
  80: "Reggio di Calabria",
  81: "Trapani",
  82: "Palermo",
  83: "Messina",
  84: "Agrigento",
  85: "Caltanissetta",
  86: "Enna",
  87: "Catania",
  88: "Ragusa",
  89: "Siracusa",
  90: "Sassari",
  91: "Nuoro",
  92: "Cagliari",
  93: "Pordenone",
  94: "Isernia",
  95: "Oristano",
  96: "Biella",
  97: "Lecco",
  98: "Lodi",
  99: "Rimini",
  100: "Prato",
  101: "Crotone",
  102: "Vibo Valentia",
  103: "Verbano-Cusio-Ossola",
  108: "Monza e della Brianza",
  109: "Fermo",
  110: "Barletta-Andria-Trani",
  111: "Sud Sardegna"
};

export const numberAxisFormatter = (n) => {
  return (n>999) ? `${n/1000}K` : n;
};

export const dateAxisFormatter = (t) => {
  return moment(t).format('DD MMM');
};

export const binArrayToJson = (binArray) => {
  let str = "";
  for (let i = 0; i < binArray.length; i++) {
    str += String.fromCharCode(parseInt(String(binArray[i])));
  }
  const json = JSON.parse(str);
  return json;
};